// <auto-generated />
using Imobiliaria.Model.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Imobiliaria.Migrations
{
    [DbContext(typeof(DbImobiliaria))]
    partial class DbImobiliariaModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Imobiliaria.Model.Cobranca", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("cobranca_paga")
                        .HasColumnType("INTEGER");

                    b.Property<int>("id_condominio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("id_morador")
                        .HasColumnType("INTEGER");

                    b.Property<string>("tipo_pagamento")
                        .HasColumnType("TEXT");

                    b.Property<double>("valor_pagamento")
                        .HasColumnType("REAL");

                    b.Property<string>("vencimento")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Cobranca");
                });

            modelBuilder.Entity("Imobiliaria.Model.Condominio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cidade_condominio")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome_condominio")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Condominios");
                });

            modelBuilder.Entity("Imobiliaria.Model.Moradores", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cep")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<int>("id_condominio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Moradores");
                });
#pragma warning restore 612, 618
        }
    }
}
